[program:apiok-stash]
directory=/opt/apiok-stash
command=/opt/apiok-stash/apiok-stash -f /opt/apiok-stash/etc/config.yaml
autostart=true
autorestart=true
startsecs=3
startretries=10
stopwaitsecs=30
stopsignal=TERM
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/opt/apiok-stash/stdout.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=10
priority=999
