Clusters:
- Input:
    File:
      Paths:
        - /var/log/apiok/access.log
      Format: plain
      Follow: true
      FromBeginning: false
  Ip2Region:
    Db: "/data/ip2region_v4.xdb"
  Filters:
    - Action: transfer
      Field: message
    - Action: parse_time
      Field: time
    - Action: ip2region
      Field: remote_addr
      Target: geo
    - Action: remove_field
      Fields:
        - message
  Output:
    MySQL:
      DSN: "apiok:YdGxr7y5nfwM7HPR@tcp(127.0.0.1:3306)/apiok"
      Table: "ok-logs-{{yyyy-MM-dd}}"
      CreateTableSQL: |
        CREATE TABLE IF NOT EXISTS `%s` (
          id bigint unsigned NOT NULL AUTO_INCREMENT,
          remote_addr VARCHAR(64) NULL,
          x_forwarded_for VARCHAR(512) NULL,
          `time` datetime NULL,
          url TEXT NULL,
          method VARCHAR(16) NULL,
          request TEXT NULL,
          request_length BIGINT NULL,
          referer TEXT NULL,
          user_agent TEXT NULL,
          connection_requests INT NULL,
          upstream_cache_status VARCHAR(64) NULL,
          status INT NULL,
          request_time DOUBLE NULL,
          upstream_response_time DOUBLE NULL,
          bytes_sent BIGINT NULL,
          body_bytes_sent BIGINT NULL,
          server_name VARCHAR(255) NULL,
          upstream_addr VARCHAR(512) NULL,
          upstream_status INT NULL,
          request_id VARCHAR(128) NULL,
          block_reason VARCHAR(512) NULL,
          block_rule VARCHAR(512) NULL,
          geo_country VARCHAR(128) NULL,
          geo_province VARCHAR(128) NULL,
          geo_city VARCHAR(128) NULL,
          geo_isp VARCHAR(128) NULL,
          geo_country_code VARCHAR(16) NULL,
          PRIMARY KEY (id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
      InsertColumns:
        - remote_addr
        - x_forwarded_for
        - time
        - url
        - method
        - request
        - request_length
        - referer
        - user_agent
        - connection_requests
        - upstream_cache_status
        - status
        - request_time
        - upstream_response_time
        - bytes_sent
        - body_bytes_sent
        - server_name
        - upstream_addr
        - upstream_status
        - request_id
        - block_reason
        - block_rule
        - geo_country
        - geo_province
        - geo_city
        - geo_isp
        - geo_country_code
      TimeZone: "Asia/Shanghai"
